### ISSUE TITLE
打开源代码编译即报错： 1. 无效的 app.json 2. Error: key值不能为空

### ISSUE THREAD

**Issue by pengyuwei** [TencentLBS/TencentMapMiniProgramDemo#4]
微信开发者工具：1.03
源代码commit号：7d169e96657dc156eae1d697421b64896b655cf7
所需插件已经安装

打开源代码编译即报错：
1. `无效的 app.json `
2. `Error: key值不能为空`

```
devtoolsconfig.js?t=wechat&s=1612223857716&v=7874b848990465bbcdadbee702a24d44:3 无效的 app.json ["servicemarket"]
(anonymous) @ devtoolsconfig.js?t=wechat&s=1612223857716&v=7874b848990465bbcdadbee702a24d44:3
VM91:210 页面【pages/map/event/event]错误:
 Error: key值不能为空
    at new QQMapWX (qqmap-wx-jssdk.min.js? [sm]:1)
    at event.js? [sm]:6
    at require (VM42 WAService.js:2)
    at <anonymous>:207:9
    at doWhenAllScriptLoaded (<anonymous>:470:21)
    at Object.scriptLoaded (<anonymous>:490:5)
    at Object.<anonymous> (<anonymous>:515:22)
(anonymous) @ VM91:210
doWhenAllScriptLoaded @ VM51:470
scriptLoaded @ VM51:490
(anonymous) @ VM51:515
Promise.then (async)
(anonymous) @ VM51:541
(anonymous) @ VM51:545
loadScripts @ assubloader.js:1
async function (async)
loadScripts @ assubloader.js:1
loadAppResourceScripts @ assubloader.js:1
(anonymous) @ instanceframe?s=1612223868936&autoload:7
VM42 WAService.js:2 MiniProgramError
key值不能为空
Error: key值不能为空
    at new QQMapWX (http://127.0.0.1:36736/appservice/utils/qqmap-wx-jssdk.min.js:240:13)
    at http://127.0.0.1:36736/appservice/pages/map/event/event.js:7:16
    at require (http://127.0.0.1:36736/appservice/__dev__/WAService.js?t=wechat&s=1612223857716&v=2.14.0:2:3253998)
    at <anonymous>:207:9
    at doWhenAllScriptLoaded (<anonymous>:470:21)
    at Object.scriptLoaded (<anonymous>:490:5)
    at Object.<anonymous> (<anonymous>:515:22)
errorReport @ VM42 WAService.js:2
thirdErrorReport @ VM42 WAService.js:2
(anonymous) @ VM42 WAService.js:2
u @ VM42 WAService.js:2
n @ VM42 WAService.js:2
(anonymous) @ VM42 WAService.js:2
value @ VM42 WAService.js:2
(anonymous) @ VM42 WAService.js:2
doWhenAllScriptLoaded @ VM51:470
scriptLoaded @ VM51:490
(anonymous) @ VM51:515
error (async)
(anonymous) @ VM42 WAService.js:2
(anonymous) @ VM42 WAService.js:2
(anonymous) @ VM42 WAService.js:2
devtoolsconfig.js?t=wechat&s=1612223857716&v=7874b848990465bbcdadbee702a24d44:3 无效的 app.json ["servicemarket"]
```

**Comment by pengyuwei** [comment]
报错代码为：
```
const qqmapsdk = new QQMapWX({
	key: 'DPEBZ-SXF6X-IDK45-7O6JH-LJZZE-KIB42' // 必填
});
```

经查，需要在[腾讯位置服务后台](https://lbs.qq.com/dev/console/key/add) 申请开发者密钥（key）才可以。
建议官方把编译步骤写在README里，减少用户学习时间。[参考文档](http://lbs.qq.com/qqmap_wx_jssdk/index.html)
